extends Node

signal ingredient_changed(data)

enum {NAME, ICON, UNIT, GROUP, INGREDIENTS, AMOUNT, OPTIONAL, UTILITY, TIME, COOKBOOK, REGION, AVAILABLE, USED} # Dictionary keys
enum {PIECES, LITERS} # Units
enum {SKEWER, BBQ, PAN, POT, OVEN} # Utilities
enum BOOK {SIMPLE, BBQ, CAKE, CASSEROLES, DRINKS, PASTA, PIZZA, RICE, SOUP, STEW} # Cookbooks. SIMPLE means no book required

const ATLAS := preload("res://textures.png")
const ATLAS_WIDTH := 16
const ICON_SIZE := Vector2(64, 64)
const DEFAULT_FONT := preload("res://default_font.tres")
const TINY_FONT := preload("res://tiny_font.tres")

const ALL_INGREDIENTS := [] # will be filled at runtime

# Also each will contain REGION, AVAILABLE and USED keys
const CHILLI := {NAME: "Chilli Pepper", ICON: 1}
const CUCUMBER := {NAME: "Cucumber", ICON: 2}
const PARSNIP := {NAME: "Parsnip", ICON: 3}
const POTATO := {NAME: "Potato", ICON: 4}
const LEMON := {NAME: "Lemon", ICON: 5}
const SODA := {NAME: "Baking Soda", ICON: 6}
const CHOCCANDY := {NAME: "ChocCandy", ICON: 7}
const FLOUR := {NAME: "Flour", ICON: 8}
const BANANA := {NAME: "Banana", ICON: 9}
const BLACK_PEPPER := {NAME: "Black Pepper", ICON: 10}
const BUTTER := {NAME: "Butter", ICON: 11}
const SUGAR := {NAME: "Sugar", ICON: 12}
const BEAR_STEAK := {NAME: "Bear Steak", ICON: 13}
const DEER_STEAK := {NAME: "Deer Steak", ICON: 13}
const DOE_STEAK := {NAME: "Doe Steak", ICON: 13}
const DONKEY_STEAK := {NAME: "Donkey Steak", ICON: 13}
const GOAT_STEAK := {NAME: "Goat Steak", ICON: 13}
const HORSE_STEAK := {NAME: "Horse Steak", ICON: 13}
const HUMAN_STEAK := {NAME: "Human Steak", ICON: 13}
const PORK_STEAK := {NAME: "Pork Steak", ICON: 13}
const WOLF_STEAK := {NAME: "Wolf Steak", ICON: 13}
const CABBAGE := {NAME: "Cabbage", ICON: 14}
const RICE := {NAME: "Rice", ICON: 15}
const WATER := {NAME: "Water", ICON: 16, UNIT: LITERS}
const SALT := {NAME: "Salt", ICON: 17}
const OIL := {NAME: "Oil", ICON: 18, UNIT: LITERS}
const CARROT := {NAME: "Carrot", ICON: 19}
const EGG := {NAME: "Egg", ICON: 20}
const YEAST := {NAME: "Yeast", ICON: 21}
const FAT := {NAME: "Animal Fat", ICON: 22}
const CHICKEN_MEAT := {NAME: "Chicken Meat", ICON: 23}
const BREAD := {NAME: "Bread", ICON: 24}
const KETCHUP := {NAME: "Ketchup", ICON: 25}
const MAYONNAISE := {NAME: "Mayonnaise", ICON: 26}
const MUSTARD := {NAME: "Mustard", ICON: 27}
const DRUMSTICK := {NAME: "Chicken Drumstick", ICON: 28}
const CORN := {NAME: "Corn", ICON: 29}
const ONION := {NAME: "Onion", ICON: 30}
const PEPPER := {NAME: "Bell Pepper", ICON: 31}
const TOMATO := {NAME: "Tomato", ICON: 32}
const ZUCCHINI := {NAME: "Zucchini", ICON: 33}
const CREAM := {NAME: "Cream", ICON: 34}
const MILK := {NAME: "Milk", ICON: 35}
const SPICES := {NAME: "Mixed Spices", ICON: 36}
const SAUCE := {NAME: "Soy Sauce", ICON: 37}
const CHEESE := {NAME: "Cheese", ICON: 38}
const SEAFOOD := {NAME: "Seafood Mix", ICON: 39}
const PEAS := {NAME: "Peas", ICON: 40}
const PINEAPPLE := {NAME: "Pineapple", ICON: 41}
const I_SUGAR := {NAME: "Icing Sugar", ICON: 42}
const AMUR_FILLET := {NAME: "Amur Fillet", ICON: 43}
const BASS_FILLET := {NAME: "Bass Fillet", ICON: 43}
const BLEAK_FILLET := {NAME: "Bleak Fillet", ICON: 43}
const CARP_FILLET := {NAME: "Carp Fillet", ICON: 43}
const CATFISH_FILLET := {NAME: "Catfish Fillet", ICON: 43}
const CHUB_FILLET := {NAME: "Chub Fillet", ICON: 43}
const DANTEX_FILLET := {NAME: "Dantex Fillet", ICON: 43}
const E_BASS_FILLET := {NAME: "European Bass Fillet", ICON: 43}
const ANGLER_FILLET := {NAME: "Angler Fillet", ICON: 43}
const ORATA_FILLET := {NAME: "Orata Fillet", ICON: 43}
const PIKE_FILLET := {NAME: "Pike Fillet", ICON: 43}
const RUFFE_FILLET := {NAME: "Ruffe Fillet", ICON: 43}
const SARDINE_FILLET := {NAME: "Sardine Fillet", ICON: 43}
const TUNA_FILLET := {NAME: "Tuna Fillet", ICON: 43}
const MUSHROOM_15 := {NAME: "Lycoperdon Gigantea", ICON: 44}
const MUSHROOM_14 := {NAME: "Lingzhi Mushroom", ICON: 45}
const MUSHROOM_13 := {NAME: "Fistula Hepatica", ICON: 46}
const MUSHROOM_12 := {NAME: "Coprinus Comatus", ICON: 47}
const MUSHROOM_11 := {NAME: "Psilocybe Cyanescens", ICON: 48}
const MUSHROOM_10 := {NAME: "Amanita Virosa", ICON: 49}
const MUSHROOM_9 := {NAME: "Amanita Phalloides", ICON: 50}
const MUSHROOM_8 := {NAME: "Amanita Pantherina", ICON: 51}
const MUSHROOM_7 := {NAME: "Amanita Muscaria", ICON: 52}
const MUSHROOM_6 := {NAME: "Lepiota Procera", ICON: 53}
const MUSHROOM_5 := {NAME: "Cantharellus Cibarius", ICON: 54}
const MUSHROOM_4 := {NAME: "Boletus Edulis", ICON: 55}
const MUSHROOM_3 := {NAME: "Armillaria Mellea", ICON: 56}
const MUSHROOM_2 := {NAME: "Agaricus Campestris", ICON: 57}
const MUSHROOM_1 := {NAME: "Agaricus Augustus", ICON: 58}
const LIQUOR := {NAME: "Liquor", ICON: 59}
const MELON := {NAME: "Cantaloupe Melon", ICON: 60}
const APPLE := {NAME: "Apple", ICON: 61}
const MANGO := {NAME: "Mango", ICON: 62}
const TANGERINE := {NAME: "Tangerine", ICON: 63}
const GARLIC := {NAME: "Garlic", ICON: 64}
const KIWI := {NAME: "Kiwi", ICON: 65}
const ORANGE := {NAME: "Orange", ICON: 66}
const GRAPEFRUIT := {NAME: "Grapefruit", ICON: 67}
const PEAR := {NAME: "Pear", ICON: 68}
const PEACH := {NAME: "Peach", ICON: 69}
const BLUEBERRIES := {NAME: "Blueberries", ICON: 70}
const TEA := {NAME: "Tea Pack", ICON: 71}
const RAISINS := {NAME: "Raisins", ICON: 72}
const COCONUT := {NAME: "Coconut", ICON: 73}
const RABBIT_MEAT := {NAME: "Rabbit Meat", ICON: 74}
const RABBIT_LEG := {NAME: "Rabbit Leg", ICON: 75}
const GUTS := {NAME: "Guts", ICON: 76}
const BEET := {NAME: "Beet", ICON: 77}
const WINE := {NAME: "Wine", ICON: 78}
const OLIVES := {NAME: "Olives", ICON: 79}
const BEANS := {NAME: "Beans", ICON: 80}
const WALNUT := {NAME: "Walnut", ICON: 81}
const LIME := {NAME: "Lime", ICON: 82}
const SPON := {NAME: "Spon", ICON: 83}
const VINEGAR := {NAME: "Vinegar", ICON: 84}
const COCOA := {NAME: "Cocoa Powder", ICON: 85}
const TOMATO_SAUCE := {NAME: "Tomato Sauce", ICON: 86}
const SUGAR_BEET := {NAME: "Sugar Beet", ICON: 87}
const PASTA := {NAME: "Pasta", ICON: 88}
const TOMATO_PELATI := {NAME: "Tomato Pelati", ICON: 89}
const L_A_BONE := {NAME: "Large Animal Bone", ICON: 90}
const CAULIFLOWER := {NAME: "Cauliflower", ICON: 91}
const R_CHEESE := {NAME: "Richard's Cheese", ICON: 92}
const CHEESE_SLICES := {NAME: "Cheese Slices", ICON: 93}
const SPINACH := {NAME: "Spinach", ICON: 94}
const CELERY := {NAME: "Celery", ICON: 95}
const C_C_CANDY := {NAME: "Chocolate Cake Candy", ICON: 96}
const CHOCOBAR := {NAME: "ChocoBar", ICON: 98}
const C_C_BAR := {NAME: "Chocolate Candy Bar", ICON: 99}
const CHOCOLATE_BAR := {NAME: "Chocolate Bar", ICON: 100}
const LETTUCE := {NAME: "Lettuce", ICON: 101}
const COFFEE := {NAME: "Coffee", ICON: 102}
const BROCCOLI := {NAME: "Broccoli", ICON: 103}
const ANIMAL_BONE := {NAME: "Animal Bone", ICON: 104}
const BONE := {NAME: "Bone", ICON: 105}
const PLUCKED_CHICKEN := {NAME: "Plucked Chicken", ICON: 106}

const POULTRY_MEAT := {NAME: "Poultry Meat", ICON: 23, GROUP: [CHICKEN_MEAT]}
const ANY_MEAT := {NAME: "Any Meat", ICON: 13, GROUP: [BEAR_STEAK, DEER_STEAK, DOE_STEAK, DONKEY_STEAK, GOAT_STEAK, HORSE_STEAK, HUMAN_STEAK, PORK_STEAK, WOLF_STEAK, CHICKEN_MEAT, POULTRY_MEAT, RABBIT_MEAT]}
const MEAT := {NAME: "Meat", ICON: 13, GROUP: [BEAR_STEAK, DEER_STEAK, DOE_STEAK, DONKEY_STEAK, GOAT_STEAK, HORSE_STEAK, HUMAN_STEAK, PORK_STEAK, WOLF_STEAK, CHICKEN_MEAT, RABBIT_MEAT]}
const STEAK := {NAME: "Steak", ICON: 13, GROUP: [BEAR_STEAK, DEER_STEAK, DOE_STEAK, DONKEY_STEAK, GOAT_STEAK, HORSE_STEAK, HUMAN_STEAK, PORK_STEAK, WOLF_STEAK]}
const POULTRY_SKINNED := {NAME: "Poultry Skinned", ICON: 106, GROUP: [PLUCKED_CHICKEN]}
const WHOLE_POULTRY := {NAME: "Whole Poultry", ICON: 106, GROUP: [PLUCKED_CHICKEN]}
const BONE_GROUP := {NAME: "Bone", ICON: 90, GROUP: [BONE, ANIMAL_BONE, L_A_BONE]}
const ANY_FISH_FILLET := {NAME: "Any Fish Fillet", ICON: 43, GROUP: [AMUR_FILLET, BASS_FILLET, BLEAK_FILLET, CARP_FILLET, CATFISH_FILLET, CHUB_FILLET, DANTEX_FILLET, E_BASS_FILLET, ANGLER_FILLET, ORATA_FILLET, PIKE_FILLET, RUFFE_FILLET, SARDINE_FILLET, TUNA_FILLET]}
const FISH_FILLET := {NAME: "Fish Fillet", ICON: 43, GROUP: [AMUR_FILLET, BASS_FILLET, BLEAK_FILLET, CARP_FILLET, CATFISH_FILLET, CHUB_FILLET, DANTEX_FILLET, E_BASS_FILLET, ANGLER_FILLET, ORATA_FILLET, PIKE_FILLET, RUFFE_FILLET, SARDINE_FILLET, TUNA_FILLET]}
const F_FISH_FILLET := {NAME: "Freshwater Fish Fillet", ICON: 43, GROUP: [AMUR_FILLET, BASS_FILLET, BLEAK_FILLET, CARP_FILLET, CATFISH_FILLET, CHUB_FILLET, PIKE_FILLET, RUFFE_FILLET]}
const S_FISH_FILLET := {NAME: "Salt Water Fish Fillet", ICON: 43, GROUP: [DANTEX_FILLET, E_BASS_FILLET, ANGLER_FILLET, ORATA_FILLET, SARDINE_FILLET, TUNA_FILLET]}
const VEGETABLES := {NAME: "Vegetables", ICON: 31, GROUP: [PEPPER, CARROT, ONION, TOMATO, ZUCCHINI, CORN, POTATO, GARLIC]}
const VEGETABLES_2 := {NAME: "Vegetables", ICON: 77, GROUP: [BEET, PEPPER, BROCCOLI, CABBAGE, CARROT, CAULIFLOWER, CELERY, CHILLI, CUCUMBER, GARLIC, LETTUCE, ONION, PARSNIP, SPINACH, SUGAR_BEET, ZUCCHINI, POTATO]}
const LEMON_LIME := {NAME: "Lemon/Lime", ICON: 5, GROUP: [LEMON, LIME]}
const MUSHROOMS := {NAME: "Mushrooms", ICON: 58, GROUP: [MUSHROOM_1, MUSHROOM_2, MUSHROOM_3, MUSHROOM_4, MUSHROOM_5, MUSHROOM_6, MUSHROOM_7, MUSHROOM_8, MUSHROOM_9, MUSHROOM_10, MUSHROOM_11, MUSHROOM_12, MUSHROOM_13, MUSHROOM_14]}
const MUSHROOMS_2 := {NAME: "Mushrooms", ICON: 58, GROUP: [MUSHROOM_1, MUSHROOM_2, MUSHROOM_3, MUSHROOM_4, MUSHROOM_5, MUSHROOM_6, MUSHROOM_7, MUSHROOM_8, MUSHROOM_9, MUSHROOM_10, MUSHROOM_11, MUSHROOM_12, MUSHROOM_13, MUSHROOM_14, MUSHROOM_15]}
const CHOCOLATE := {NAME: "Chocolate", ICON: 97, GROUP: [CHOCCANDY, CHOCOBAR, C_C_BAR, C_C_CANDY, CHOCOLATE_BAR]}
const CHEESE_2 := {NAME: "Cheese", ICON: 38, GROUP: [CHEESE, R_CHEESE]}
const CHEESE_3 := {NAME: "Any Cheese", ICON: 38, GROUP: [CHEESE_SLICES, R_CHEESE]}
const TOMATO_2 := {NAME: "Tomato", ICON: 32, GROUP: [TOMATO, TOMATO_SAUCE]}
const TOMATO_3 := {NAME: "Tomato Sauce", ICON: 32, GROUP: [TOMATO, TOMATO_PELATI]}
const PARSLEY := {NAME: "Parsley", ICON: 3, GROUP: [PARSNIP]}
const ANY_FRUIT := {NAME: "Any Fruit", ICON: 61, GROUP: [APPLE, BANANA, BLUEBERRIES, MELON, GRAPEFRUIT, KIWI, LEMON, LIME, MANGO, ORANGE, PEACH, PEAR, PINEAPPLE, TANGERINE]}

const RECIPES := [
	{NAME: "Poultry Drumstick", INGREDIENTS: [DRUMSTICK, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 15, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Grilled Veggie", INGREDIENTS: [VEGETABLES, SALT, BLACK_PEPPER, VEGETABLES, VEGETABLES, VEGETABLES, VEGETABLES], AMOUNT: [1, 1, 1, 1, 1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 1, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Grilled Sausage", INGREDIENTS: [STEAK, GUTS, SALT, MUSTARD, BLACK_PEPPER], AMOUNT: [1, 1, 1, 1, 1], OPTIONAL: 2, UTILITY: [BBQ, PAN], TIME: 4, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Grilled Red Meat", INGREDIENTS: [STEAK, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 8, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Grilled Rabbit Leg", INGREDIENTS: [RABBIT_LEG, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 15, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Grilled Poultry Meat", INGREDIENTS: [POULTRY_MEAT, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 8, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Grilled Mushroom", INGREDIENTS: [MUSHROOMS_2, SALT, BLACK_PEPPER, MUSHROOMS_2, MUSHROOMS_2, MUSHROOMS_2, MUSHROOMS_2], AMOUNT: [1, 1, 1, 1, 1, 1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 5, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Grilled Fish", INGREDIENTS: [FISH_FILLET, SALT, OIL, FISH_FILLET], AMOUNT: [1, 1, 0.1, 1], OPTIONAL: 1, UTILITY: [BBQ, PAN], TIME: 5, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Cheeseburger", INGREDIENTS: [STEAK, BREAD, CHEESE_3, SALT, BLACK_PEPPER, KETCHUP, MAYONNAISE], AMOUNT: [1, 1, 1, 1, 1, 1, 1], OPTIONAL: 3, UTILITY: [BBQ, PAN], TIME: 10, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Cevapi", INGREDIENTS: [STEAK, BREAD, SALT, BLACK_PEPPER, ONION], AMOUNT: [1, 2, 1, 1, 1], OPTIONAL: 2, UTILITY: [BBQ, PAN], TIME: 10, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Burger", INGREDIENTS: [STEAK, BREAD, SALT, BLACK_PEPPER, KETCHUP, MAYONNAISE], AMOUNT: [1, 1, 1, 1, 1, 1], OPTIONAL: 2, UTILITY: [BBQ, PAN], TIME: 10, COOKBOOK: BOOK.BBQ}, 
	{NAME: "Meat Skewer", INGREDIENTS: [MEAT, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [SKEWER], TIME: 12, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Fish Skewer", INGREDIENTS: [ANY_FISH_FILLET, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1], OPTIONAL: 1, UTILITY: [SKEWER], TIME: 12, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Mixed Skewer", INGREDIENTS: [MEAT, VEGETABLES, MUSHROOMS_2, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1, 2, 2], OPTIONAL: 3, UTILITY: [SKEWER], TIME: 10, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Vegetable Skewer", INGREDIENTS: [VEGETABLES, MUSHROOMS_2, SALT, BLACK_PEPPER, VEGETABLES, VEGETABLES], AMOUNT: [1, 1, 2, 2, 1, 1], OPTIONAL: 2, UTILITY: [SKEWER], TIME: 8, COOKBOOK: BOOK.SIMPLE}, 
	{NAME: "Tea Cookies", INGREDIENTS: [EGG, SUGAR, FLOUR, MILK, SODA, CREAM, BUTTER, SALT], AMOUNT: [1, 5, 5, 0.2, 2, 1, 2, 2], OPTIONAL: 6, UTILITY: [OVEN], TIME: 30, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Pancakes", INGREDIENTS: [FLOUR, EGG, MILK, WATER, SODA, SALT, BUTTER, OIL, WALNUT, SUGAR], AMOUNT: [3, 1, 0.25, 0.25, 2, 1, 2, 0.1, 1, 5], OPTIONAL: 5, UTILITY: [PAN], TIME: 8, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Lamington Cake", INGREDIENTS: [FLOUR, EGG, SUGAR, MILK, CHOCOLATE, COCONUT, OIL, SODA, BUTTER, LIQUOR], AMOUNT: [5, 1, 5, 0.5, 1, 1, 0.3, 2, 1, 0.1], OPTIONAL: 8, UTILITY: [OVEN], TIME: 80, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Fruit Cake", INGREDIENTS: [ANY_FRUIT, ANY_FRUIT, EGG, SUGAR, FLOUR, MILK, SODA, BUTTER, ANY_FRUIT, ANY_FRUIT], AMOUNT: [1, 1, 1, 5, 5, 0.2, 1, 2, 1, 1], OPTIONAL: 7, UTILITY: [OVEN], TIME: 120, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Cream Slice", INGREDIENTS: [EGG, EGG, FLOUR, WATER, SUGAR, CREAM, I_SUGAR], AMOUNT: [1, 1, 5, 0.25, 5, 1, 4], OPTIONAL: 6, UTILITY: [OVEN], TIME: 120, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Chocolote Roulade", INGREDIENTS: [CHOCOLATE, EGG, FLOUR, SUGAR, CREAM, EGG, BUTTER, SODA, COCOA], AMOUNT: [1, 1, 1, 5, 1, 1, 1, 1, 2], OPTIONAL: 8, UTILITY: [OVEN], TIME: 45, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Chocolote Cake", INGREDIENTS: [CHOCOLATE, CHOCOLATE, EGG, FLOUR, SUGAR, CREAM, SALT, OIL, BUTTER], AMOUNT: [1, 1, 1, 5, 5, 1, 1, 0.1, 2], OPTIONAL: 6, UTILITY: [OVEN], TIME: 60, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Cheese Cake", INGREDIENTS: [EGG, FLOUR, SUGAR, CREAM, COFFEE, CHEESE_2, SALT, BUTTER, MILK, OIL, RAISINS], AMOUNT: [1, 2, 5, 1, 1, 1, 1, 2, 0.1, 0.2, 2], OPTIONAL: 6, UTILITY: [OVEN], TIME: 60, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Bread", INGREDIENTS: [FLOUR, MILK, WATER, SODA, YEAST, SALT, FAT, SUGAR], AMOUNT: [1, 0.1, 0.5, 2, 1, 1, 1, 2], OPTIONAL: 5, UTILITY: [OVEN], TIME: 15, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Banana Cake", INGREDIENTS: [BANANA, BANANA, EGG, FLOUR, SUGAR, CREAM, SALT, BUTTER, I_SUGAR, CHEESE_2], AMOUNT: [1, 1, 1, 5, 5, 1, 1, 2, 4, 1], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Baklava", INGREDIENTS: [FLOUR, WATER, BUTTER, SUGAR, WALNUT, WALNUT, LEMON, SALT, OIL], AMOUNT: [5, 0.25, 1, 1, 1, 1, 1, 1, 0.2], OPTIONAL: 6, UTILITY: [OVEN], TIME: 120, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Apple Pie", INGREDIENTS: [APPLE, APPLE, APPLE, FLOUR, FAT, SUGAR, SODA, SALT, WALNUT, WALNUT, RAISINS, I_SUGAR], AMOUNT: [1, 1, 1, 5, 1, 5, 1, 1, 1, 1, 2, 4], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CAKE}, 
	{NAME: "Poultry Casserole", INGREDIENTS: [POULTRY_MEAT, POULTRY_MEAT, ONION, OLIVES, WATER, BEANS, SALT, BLACK_PEPPER, SPICES, OIL, GARLIC], AMOUNT: [1, 1, 1, 1, 0.5, 1, 2, 2, 1, 0.2, 1], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Moussaka", INGREDIENTS: [MEAT, POTATO, POTATO, ONION, CREAM, EGG, SALT, BLACK_PEPPER, OIL, BUTTER, MILK, CHEESE_2], AMOUNT: [1, 1, 1, 1, 1, 1, 2, 2, 0.3, 2, 0.25, 1], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Meat Pie", INGREDIENTS: [MEAT, EGG, ONION, OIL, FLOUR, WATER, SALT, BLACK_PEPPER, CREAM], AMOUNT: [1, 1, 1, 0.3, 6, 0.2, 2, 2, 1], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Mac And Cheese", INGREDIENTS: [PASTA, CHEESE_2, CHEESE_2, WATER, MILK, SALT, BLACK_PEPPER, OIL, BUTTER, FLOUR], AMOUNT: [1, 1, 1, 1.0, 0.5, 2, 2, 0.2, 2, 1], OPTIONAL: 5, UTILITY: [OVEN], TIME: 30, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Lasagna", INGREDIENTS: [STEAK, CHEESE_2, ONION, EGG, FLOUR, WATER, CREAM, SALT, BLACK_PEPPER, OIL, MILK, BUTTER], AMOUNT: [1, 1, 1, 1, 5, 0.1, 1, 2, 1, 0.3, 0.5, 1], OPTIONAL: 7, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Fried Eggs", INGREDIENTS: [EGG, SALT, OIL, EGG, EGG, EGG], AMOUNT: [1, 1, 0.1, 1, 1, 1], OPTIONAL: 1, UTILITY: [PAN], TIME: 5, COOKBOOK: BOOK.SIMPLE},
	{NAME: "Dauphinoise Potatoes", INGREDIENTS: [POTATO, POTATO, CHEESE_2, FLOUR, MILK, CREAM, BUTTER, SALT, BLACK_PEPPER, OIL], AMOUNT: [1, 1, 1, 1, 0.2, 1, 1, 2, 1, 0.3], OPTIONAL: 7, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Cheese Pie", INGREDIENTS: [CHEESE_2, EGG, CREAM, OIL, FLOUR, WATER, SALT], AMOUNT: [1, 1, 1, 0.8, 6, 0.2, 2], OPTIONAL: 6, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Cheese Loaves", INGREDIENTS: [CHEESE_2, FLOUR, EGG, WATER, SALT, OIL, VINEGAR], AMOUNT: [1, 1, 1, 1, 0.5, 2, 0.3, 0.1], OPTIONAL: 5, UTILITY: [OVEN], TIME: 90, COOKBOOK: BOOK.CASSEROLES},
	{NAME: "Tea", INGREDIENTS: [TEA, WATER, SUGAR, LEMON_LIME], AMOUNT: [1, 0.5, 1, 1], OPTIONAL: 2, UTILITY: [POT], TIME: 3, COOKBOOK: BOOK.SIMPLE},
	{NAME: "Hot Chocolate", INGREDIENTS: [CREAM, CHOCOLATE, MILK, SUGAR], AMOUNT: [1, 1, 0.5, 1], OPTIONAL: 3, UTILITY: [POT], TIME: 10, COOKBOOK: BOOK.DRINKS},
	{NAME: "English Tea", INGREDIENTS: [TEA, WATER, MILK, SUGAR], AMOUNT: [1, 0.5, 0.1, 1], OPTIONAL: 3, UTILITY: [POT], TIME: 3, COOKBOOK: BOOK.DRINKS},
	{NAME: "Coffee Espresso Con Panna", INGREDIENTS: [COFFEE, WATER, MILK, CREAM, SUGAR], AMOUNT: [1, 0.5, 0.1, 1, 1], OPTIONAL: 4, UTILITY: [POT], TIME: 5, COOKBOOK: BOOK.DRINKS},
	{NAME: "Coffee Black", INGREDIENTS: [COFFEE, WATER, SUGAR], AMOUNT: [1, 0.5, 1], OPTIONAL: 2, UTILITY: [POT], TIME: 5, COOKBOOK: BOOK.SIMPLE},
	{NAME: "Vegetable Pasta", INGREDIENTS: [VEGETABLES_2, VEGETABLES_2, PASTA, WATER, SALT, BLACK_PEPPER, OIL, VEGETABLES_2, VEGETABLES_2], AMOUNT: [1, 1, 1, 1.0, 2, 2, 0.2, 1, 1], OPTIONAL: 4, UTILITY: [POT, PAN], TIME: 30, COOKBOOK: BOOK.PASTA},
	{NAME: "Szechuan Noodles", INGREDIENTS: [PASTA, WATER, MEAT, MEAT, CHILLI, PEPPER, ONION, SALT, OIL, SPICES, SAUCE, VINEGAR], AMOUNT: [1, 0.1, 1, 1, 1, 1, 1, 2, 0.2, 2, 0.2, 0.25], OPTIONAL: 7, UTILITY: [PAN], TIME: 60, COOKBOOK: BOOK.PASTA},
	{NAME: "Spaghetti Milanese", INGREDIENTS: [PASTA, TOMATO, CHEESE_2, WATER, ONION, SALT, BLACK_PEPPER, SPICES, OIL, FLOUR, GARLIC], AMOUNT: [1, 1, 1, 1.0, 1, 2, 2, 2, 0.2, 1, 1], OPTIONAL: 5, UTILITY: [POT, PAN], TIME: 30, COOKBOOK: BOOK.PASTA},
	{NAME: "Spaghetti Bolognese", INGREDIENTS: [PASTA, CHEESE_2, WATER, ONION, STEAK, SALT, BLACK_PEPPER, OIL, SPICES, GARLIC, WINE], AMOUNT: [1, 1, 1.0, 1, 1, 2, 2, 0.2, 2, 1, 0.2], OPTIONAL: 5, UTILITY: [POT, PAN], TIME: 30, COOKBOOK: BOOK.PASTA},
	{NAME: "Seafood Pasta", INGREDIENTS: [PASTA, SEAFOOD, CREAM, WATER, GARLIC, ONION, SALT, BLACK_PEPPER, OIL, WINE, BUTTER, OLIVES], AMOUNT: [1, 1, 1, 1.0, 1, 1, 2, 2, 0.2, 0.2, 1, 1], OPTIONAL: 6, UTILITY: [POT, PAN], TIME: 45, COOKBOOK: BOOK.PASTA},
	{NAME: "Pesto Penne Pasta", INGREDIENTS: [PASTA, TOMATO_2, CHEESE_2, WATER, SALT, BLACK_PEPPER, OIL, SPICES], AMOUNT: [1, 1, 1, 1.0, 2, 2, 0.2, 2], OPTIONAL: 4, UTILITY: [POT, PAN], TIME: 30, COOKBOOK: BOOK.PASTA},
	{NAME: "Mushroom Pasta", INGREDIENTS: [MUSHROOMS, MUSHROOMS, MUSHROOMS, MUSHROOMS, PASTA, WATER, SALT, BLACK_PEPPER, OIL, ONION, GARLIC, MUSHROOMS, MUSHROOMS, MUSHROOMS], AMOUNT: [1, 1, 1, 1, 1, 1.0, 2, 2, 0.2, 1, 1, 1, 1, 1], OPTIONAL: 6, UTILITY: [POT, PAN], TIME: 30, COOKBOOK: BOOK.PASTA},
	{NAME: "Kung Pao Spaghetti", INGREDIENTS: [PASTA, WATER, POULTRY_MEAT, ONION, CHILLI, PEPPER, SALT, OIL, SPICES, SAUCE, VINEGAR], AMOUNT: [1, 1.0, 1, 1, 1, 1, 2, 0.2, 2, 0.2, 0.25], OPTIONAL: 6, UTILITY: [PAN], TIME: 60, COOKBOOK: BOOK.PASTA},
	{NAME: "Chow Mein", INGREDIENTS: [PASTA, POULTRY_MEAT, POULTRY_MEAT, WATER, VEGETABLES_2, SALT, BLACK_PEPPER, OIL, SAUCE, VINEGAR, SPICES, GARLIC], AMOUNT: [1, 1, 1, 1.0, 1, 2, 2, 0.2, 0.2, 0.25, 2, 1], OPTIONAL: 5, UTILITY: [PAN], TIME: 60, COOKBOOK: BOOK.PASTA},
	{NAME: "Pizza Vegetarian", INGREDIENTS: [MILK, WATER, FLOUR, CHEESE_2, YEAST, TOMATO_3, VEGETABLES_2, MUSHROOMS, SALT, OIL, SPICES, VEGETABLES_2], AMOUNT: [0.1, 0.3, 5, 1, 1, 1, 1, 1, 2, 0.2, 2, 1], OPTIONAL: 8, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Pizza Neapolitan", INGREDIENTS: [WATER, FLOUR, CHEESE_2, YEAST, TOMATO_3, SALT, OIL, SPICES, OLIVES], AMOUNT: [0.3, 5, 1, 1, 1, 2, 0.2, 2, 1], OPTIONAL: 5, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Pizza Hawaii", INGREDIENTS: [MILK, WATER, FLOUR, CHEESE_2, YEAST, SPON, PINEAPPLE, TOMATO_3, SALT, OIL, SPICES], AMOUNT: [0.1, 0.3, 5, 1, 1, 1, 1, 1, 2, 0.2, 2], OPTIONAL: 8, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Pizza Funghi", INGREDIENTS: [MILK, WATER, FLOUR, CHEESE_2, YEAST, TOMATO_3, MUSHROOMS, MUSHROOMS, SALT, OIL, SPICES], AMOUNT: [0.1, 0.3, 5, 1, 1, 1, 1, 1, 2, 0.2, 2], OPTIONAL: 8, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Pizza Frutti Mare", INGREDIENTS: [MILK, WATER, FLOUR, CHEESE_2, YEAST, TOMATO_3, SEAFOOD, SALT, OIL, SPICES, OLIVES], AMOUNT: [0.1, 0.3, 5, 1, 1, 1, 1, 2, 0.2, 2, 1], OPTIONAL: 7, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Pizza Capricciosa", INGREDIENTS: [MILK, WATER, FLOUR, CHEESE_2, YEAST, TOMATO_3, SPON, MUSHROOMS, SALT, OIL, SPICES, OLIVES], AMOUNT: [0.1, 0.3, 5, 1, 1, 1, 1, 1, 2, 0.2, 2, 1], OPTIONAL: 8, UTILITY: [OVEN], TIME: 10, COOKBOOK: BOOK.PIZZA},
	{NAME: "Spicy Szechuan", INGREDIENTS: [RICE, WATER, MEAT, ONION, CHILLI, PEPPER, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE, VINEGAR], AMOUNT: [4, 1.0, 1, 1, 1, 1, 2, 2, 0.2, 2, 0.2, 0.25], OPTIONAL: 6, UTILITY: [PAN, POT], TIME: 30, COOKBOOK: BOOK.RICE},
	{NAME: "Rice and Peas with Meat", INGREDIENTS: [RICE, PEAS, WATER, MEAT, MEAT, ONION, SALT, BLACK_PEPPER, OIL, GARLIC], AMOUNT: [4, 1, 1.0, 1, 1, 1, 2, 2, 0.2, 1], OPTIONAL: 6, UTILITY: [PAN, POT], TIME: 50, COOKBOOK: BOOK.RICE}, 
	{NAME: "Peking Duck", INGREDIENTS: [RICE, WHOLE_POULTRY, ONION, CUCUMBER, WATER, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [4, 1, 1, 1, 1.0, 2, 2, 0.2, 2, 0.2], OPTIONAL: 5, UTILITY: [PAN, POT], TIME: 20, COOKBOOK: BOOK.RICE}, 
	{NAME: "Meat Broccoli Stir Fry", INGREDIENTS: [MEAT, RICE, WATER, PEPPER, ONION, BROCCOLI, SALT, OIL, SPICES, SAUCE, CHILLI, SUGAR], AMOUNT: [1, 4, 0.5, 1, 1, 1, 2, 0.2, 2, 0.2, 1, 2], OPTIONAL: 6, UTILITY: [PAN, POT], TIME: 30, COOKBOOK: BOOK.RICE}, 
	{NAME: "Gyuvech", INGREDIENTS: [RICE, ONION, WATER, PEPPER, ZUCCHINI, CARROT, TOMATO_2, MEAT, SALT, BLACK_PEPPER, OIL, SPICES], AMOUNT: [4, 1, 0.5, 1, 1, 1, 1, 1, 2, 2, 0.2, 2], OPTIONAL: 8, UTILITY: [PAN, POT], TIME: 90, COOKBOOK: BOOK.RICE}, 
	{NAME: "General Tso's Poultry", INGREDIENTS: [POULTRY_MEAT, RICE, PEPPER, WATER, BROCCOLI, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [1, 4, 1, 0.5, 1, 2, 2, 0.2, 2, 0.2], OPTIONAL: 5, UTILITY: [PAN, POT], TIME: 30, COOKBOOK: BOOK.RICE}, 
	{NAME: "Fried Rice", INGREDIENTS: [RICE, GARLIC, EGG, ONION, PEAS, CARROT, WATER, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [4, 1, 1, 1, 1, 1, 0.5, 2, 2, 0.2, 2, 0.2], OPTIONAL: 7, UTILITY: [PAN, POT], TIME: 20, COOKBOOK: BOOK.RICE}, 
	{NAME: "Curry with Rice", INGREDIENTS: [RICE, ONION, WATER, TOMATO, MEAT, MEAT, SPICES, SALT, BLACK_PEPPER, OIL, GARLIC], AMOUNT: [4, 1, 1.0, 1, 1, 1, 2, 2, 2, 0.2, 2], OPTIONAL: 7, UTILITY: [PAN, POT], TIME: 30, COOKBOOK: BOOK.RICE}, 
	{NAME: "Chili Oiled Smashed Cucumbers", INGREDIENTS: [RICE, WATER, CUCUMBER, CHILLI, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [4, 1.0, 1, 1, 2, 2, 0.2, 2, 0.2], OPTIONAL: 4, UTILITY: [PAN, POT], TIME: 30, COOKBOOK: BOOK.RICE}, 
	{NAME: "Black Pepper Poultry", INGREDIENTS: [RICE, BLACK_PEPPER, POULTRY_MEAT, POULTRY_MEAT, WATER, PEPPER, ONION, SALT, OIL, SPICES, SAUCE, WINE], AMOUNT: [4, 1, 1, 1, 0.5, 1, 1, 2, 0.2, 2, 0.2, 0.25], OPTIONAL: 7, UTILITY: [PAN, POT], TIME: 60, COOKBOOK: BOOK.RICE}, 
	{NAME: "Wonton Soup", INGREDIENTS: [MEAT, WATER, CABBAGE, PASTA, SEAFOOD, ONION, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [1, 2.0, 1, 1, 1, 1, 2, 2, 0.2, 2, 0.2], OPTIONAL: 6, UTILITY: [POT], TIME: 20, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Tomato Soup", INGREDIENTS: [TOMATO, TOMATO, CREAM, WATER, CHEESE_2, ONION, SALT, BLACK_PEPPER, OIL, SPICES, GARLIC], AMOUNT: [1, 1, 1, 2.0, 1, 1, 2, 2, 0.2, 1, 1], OPTIONAL: 6, UTILITY: [POT], TIME: 16, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Poultry Soup", INGREDIENTS: [POULTRY_SKINNED, ONION, CARROT, WATER, PARSNIP, SALT, BLACK_PEPPER, OIL, SPICES], AMOUNT: [1, 1, 1, 2.0, 1, 2, 2, 0.2, 1], OPTIONAL: 5, UTILITY: [POT], TIME: 20, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Mushroom Soup", INGREDIENTS: [MUSHROOMS, MUSHROOMS, MUSHROOMS, ONION, WATER, CREAM, FLOUR, SALT, BLACK_PEPPER, OIL, SPICES, WINE, MUSHROOMS, MUSHROOMS], AMOUNT: [1, 1, 1, 1, 2.0, 1, 2, 2, 2, 0.2, 1, 0.25, 1, 1], OPTIONAL: 7, UTILITY: [POT], TIME: 16, COOKBOOK: BOOK.SOUP},
	{NAME: "Meat Soup", INGREDIENTS: [BONE_GROUP, STEAK, CARROT, WATER, PARSLEY, SALT, BLACK_PEPPER, OIL, SPICES, MEAT], AMOUNT: [1, 1, 1, 2.0, 1, 2, 2, 0.2, 1, 1], OPTIONAL: 5, UTILITY: [POT], TIME: 20, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Hot And Sour Soup", INGREDIENTS: [POULTRY_MEAT, MUSHROOMS_2, EGG, FLOUR, WATER, VINEGAR, SALT, BLACK_PEPPER, OIL, SPICES, CHILLI, SAUCE], AMOUNT: [1, 1, 1, 2, 2.0, 0.2, 2, 2, 0.2, 1, 1, 0.2], OPTIONAL: 6, UTILITY: [POT], TIME: 20, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Egg Drop Soup", INGREDIENTS: [POULTRY_MEAT, EGG, WATER, FLOUR, SALT, BLACK_PEPPER, OIL, SPICES, SAUCE], AMOUNT: [1, 1, 2.0, 2, 2, 2, 0.2, 1, 0.2], OPTIONAL: 4, UTILITY: [POT], TIME: 20, COOKBOOK: BOOK.SOUP}, 
	{NAME: "Seafood Stew", INGREDIENTS: [S_FISH_FILLET, ONION, WATER, GARLIC, TOMATO, SEAFOOD, SALT, BLACK_PEPPER, OIL, WINE], AMOUNT: [1, 1, 1.0, 1, 1, 1, 2, 2, 0.3, 0.2], OPTIONAL: 6, UTILITY: [POT], TIME: 60, COOKBOOK: BOOK.STEW}, 
	{NAME: "Meat Stew", INGREDIENTS: [STEAK, WATER, VEGETABLES, VEGETABLES, VEGETABLES, MUSHROOMS_2, SALT, OIL, STEAK, PEAS, WINE], AMOUNT: [1, 1.0, 1, 1, 1, 1, 2, 0.3, 1, 2, 0.5], OPTIONAL: 6, UTILITY: [POT], TIME: 90, COOKBOOK: BOOK.STEW}, 
	{NAME: "Jambalaya", INGREDIENTS: [ANY_MEAT, ANY_MEAT, VEGETABLES, SEAFOOD, GARLIC, RICE, WATER, OIL, SPICES, CHILLI, SALT, BLACK_PEPPER], AMOUNT: [1, 1, 1, 1, 1, 4, 1.0, 0.3, 4, 1, 2, 2], OPTIONAL: 7, UTILITY: [POT], TIME: 60, COOKBOOK: BOOK.STEW},
	{NAME: "Goulash", INGREDIENTS: [STEAK, VEGETABLES, VEGETABLES, VEGETABLES, WATER, MUSHROOMS_2, CHILLI, SALT, BLACK_PEPPER, OIL, FLOUR], AMOUNT: [1, 1, 1, 1, 1.0, 1, 1, 2, 2, 0.3, 3], OPTIONAL: 6, UTILITY: [POT], TIME: 120, COOKBOOK: BOOK.STEW},
	{NAME: "Fish Paprikash", INGREDIENTS: [F_FISH_FILLET, ONION, WATER, TOMATO_2, SALT, BLACK_PEPPER, CHILLI, WINE, F_FISH_FILLET, F_FISH_FILLET], AMOUNT: [1, 1, 1.0, 1, 2, 2, 1, 0.5, 1, 1], OPTIONAL: 4, UTILITY: [POT], TIME: 60, COOKBOOK: BOOK.STEW},
	{NAME: "Chilli Con Carne", INGREDIENTS: [STEAK, BEANS, WATER, GARLIC, CORN, CHILLI, TOMATO, SALT, BLACK_PEPPER, OIL, ONION, PEPPER], AMOUNT: [1, 1, 2.5, 1, 1, 1, 1, 2, 2, 0.2, 1, 1], OPTIONAL: 7, UTILITY: [POT], TIME: 60, COOKBOOK: BOOK.STEW},
	{NAME: "Cabbage Rolls", INGREDIENTS: [STEAK, STEAK, CABBAGE, RICE, WATER, SALT, BLACK_PEPPER, OIL, FLOUR, CARROT], AMOUNT: [1, 1, 1, 4, 1.0, 2, 2, 0.2, 2, 1], OPTIONAL: 5, UTILITY: [POT], TIME: 180, COOKBOOK: BOOK.STEW},
	{NAME: "Bean Stew", INGREDIENTS: [STEAK, BEANS, GARLIC, ONION, WATER, SALT, BLACK_PEPPER, OIL, TOMATO, CARROT], AMOUNT: [1, 1, 1, 1, 2.5, 2, 2, 0.2, 1, 1], OPTIONAL: 5, UTILITY: [POT], TIME: 120, COOKBOOK: BOOK.STEW}
	]

static func get_icon_region(index: int) -> Rect2:
	return Rect2(ICON_SIZE * Vector2(index % ATLAS_WIDTH, index / ATLAS_WIDTH), ICON_SIZE)
